import type { DataSource, GroupDecision, RecordGroup } from '../models/types';
import { recordLabel } from '../services/consolidation';
import { statusText } from './RecordsTable';
export function AuditView({ groups, sources, decisions, onDecision, onDetail }: { groups: RecordGroup[]; sources: DataSource[]; decisions: Record<string, GroupDecision>; onDecision: (id: string, decision: GroupDecision) => void; onDetail: (g: RecordGroup) => void }) {
  const flagged = groups.filter(g => g.status !== 'unique');
  return <section className="panel"><div className="panel-heading"><div><h2>Revisión de coincidencias y diferencias</h2><p>Las coincidencias no bloquean la exportación. Los campos sin decisión conservan la primera aportación.</p></div><span className="badge">{flagged.length} registros</span></div><div className="audit-list">{flagged.map(group => <article className="audit-item" key={group.id}><div className="panel-heading"><div><span className={`badge ${group.status}`}>{statusText[group.status]}</span><h3>{recordLabel(group.resolved, group.section)}</h3><p>{group.section.label} · {group.sourceIds.map(id => sources.find(s => s.id === id)?.name).join(', ')}</p></div><button className="button secondary small" onClick={() => onDetail(group)}>Ver procedencia</button></div>
    {!group.conflicts.length && <p className="muted">{group.status === 'exact' ? 'Se exportará una sola vez, conservando todos los orígenes en el sitio.' : group.status === 'possible' ? 'Comparten una referencia, pero tienen contenido diferente. Se conservan como registros independientes.' : 'Los campos capturados se complementan y se exportarán juntos.'}</p>}
    {group.conflicts.map(conflict => { const field = group.section.fields.find(f => f.id === conflict.fieldId)!; const decision = decisions[group.id]?.fields?.[field.id]; return <div className="conflict-field" key={field.id}><div><strong>{field.label}</strong><span className={`badge ${conflict.resolved ? 'unique' : 'conflict'}`}>{conflict.resolved ? 'Resuelto' : 'Pendiente'}</span></div><div className="conflict-candidates">{conflict.candidates.map(c => <label key={c.recordId} className={decision?.recordId === c.recordId ? 'chosen' : ''}><input type="radio" name={`${group.id}:${field.id}`} checked={decision?.mode === 'record' && decision.recordId === c.recordId} onChange={() => onDecision(group.id, { ...decisions[group.id], fields: { ...decisions[group.id]?.fields, [field.id]: { mode: 'record', recordId: c.recordId } } })}/><span><small>{sources.find(s => s.id === c.sourceId)?.name}</small><strong>{String(c.value)}</strong></span></label>)}</div><div className="button-row">{conflict.candidates.every(c => typeof c.value === 'number') && <button className={`button small ${decision?.mode === 'sum' ? 'primary' : 'secondary'}`} title="Úsalo sólo si las poblaciones de las fuentes no se superponen" onClick={() => onDecision(group.id, { ...decisions[group.id], fields: { ...decisions[group.id]?.fields, [field.id]: { mode: 'sum' } } })}>Sumar aportaciones independientes</button>}{field.type === 'text' && <button className={`button small ${decision?.mode === 'combine' ? 'primary' : 'secondary'}`} onClick={() => onDecision(group.id, { ...decisions[group.id], fields: { ...decisions[group.id]?.fields, [field.id]: { mode: 'combine' } } })}>Conservar ambos textos</button>}</div></div>; })}
    {group.section.kind === 'annex' && group.records.length > 1 && <button className="button secondary small" onClick={() => onDecision(group.id, { ...decisions[group.id], separate: true })}>Conservar como registros independientes</button>}
    </article>)}{!flagged.length && <div className="quiet-empty">No hay coincidencias ni conflictos en esta selección.</div>}</div></section>;
}
