import { ArrowUpRight, Files, Layers3, ScanLine, Copy, GitCompareArrows, Plus, Upload, FlaskConical } from 'lucide-react';
import type { DataSource, RecordGroup, WorkbookSchema } from '../models/types';
import { coverage, fieldCount } from '../services/consolidation';
export function Stats({ groups, sources, schema }: { groups: RecordGroup[]; sources: DataSource[]; schema: WorkbookSchema }) {
  const data = [
    { label: 'Fuentes de información', value: sources.length, detail: `${sources.filter(s => s.kind === 'real').length} archivos importados`, icon: Files },
    { label: 'Registros consolidados', value: groups.length, detail: `${groups.reduce((n, g) => n + fieldCount(g.resolved), 0).toLocaleString('es-MX')} campos capturados`, icon: Layers3 },
    { label: 'Cobertura cuantitativa', value: `${coverage(groups, schema).percentage}%`, detail: `${coverage(groups, schema).filled} de ${coverage(groups, schema).expected} campos`, icon: ScanLine },
    { label: 'Coincidencias', value: groups.filter(g => ['exact', 'possible'].includes(g.status)).length, detail: 'Exactas y posibles', icon: Copy },
    { label: 'Conflictos pendientes', value: groups.filter(g => g.conflicts.some(c => !c.resolved)).length, detail: 'Registros con diferencias', icon: GitCompareArrows },
  ];
  return <div className="stats-grid">{data.map(({ label, value, detail, icon: Icon }) => <article className="stat" key={label}><div><span>{label}</span><Icon size={18}/></div><strong>{typeof value === 'number' ? value.toLocaleString('es-MX') : value}</strong><small>{detail}</small></article>)}</div>;
}
export function Bars({ title, subtitle, items, onSelect }: { title: string; subtitle: string; items: { id: string; label: string; value: number; hint?: string }[]; onSelect?: (id: string) => void }) {
  const max = Math.max(1, ...items.map(i => i.value));
  return <section className="panel"><div className="panel-heading"><div><h2>{title}</h2><p>{subtitle}</p></div><span className="chart-unit">Registros</span></div><div className="bar-chart">{items.length ? items.map(item => <button key={item.id} className="bar-row" title={item.hint ?? `${item.label}: ${item.value} registros`} onClick={() => onSelect?.(item.id)} disabled={!onSelect}><span className="bar-label">{item.label}</span><span className="bar-track"><span style={{ width: `${item.value / max * 100}%` }}/></span><strong>{item.value}</strong></button>) : <div className="quiet-empty">Sin aportaciones para este filtro</div>}<div className="chart-axis"><span>0</span><span>{Math.ceil(max / 2)}</span><span>{max}</span></div></div></section>;
}
export function Dashboard({ groups, sources, schema, onIndicator, onSource, onImport, onAdd, onDemo, showEmpty }: { groups: RecordGroup[]; sources: DataSource[]; schema: WorkbookSchema; onIndicator: (id: number) => void; onSource: (id: string) => void; onImport: () => void; onAdd: () => void; onDemo: () => void; showEmpty: boolean }) {
  const indicators = Array.from({ length: 20 }, (_, i) => i + 1);
  return <>
    {showEmpty && <section className="start-panel"><div className="start-symbol"><Files size={35}/></div><div><p className="eyebrow">CONSOLIDACIÓN INSTITUCIONAL</p><h2>Tu información, en un solo lugar.</h2><p>Importa las capturas de las áreas o agrega tu primer registro.</p><div className="button-row"><button className="button primary" onClick={onImport}><Upload size={17}/>Importar Excel</button><button className="button secondary" onClick={onAdd}><Plus size={17}/>Agregar registro</button><button className="button text" onClick={onDemo}><FlaskConical size={17}/>Usar datos ficticios</button></div></div><div className="start-count"><strong>20</strong><span>indicadores SEAES</span><small>CAI 2026</small></div></section>}
    <section className="panel"><div className="panel-heading"><div><h2>Cobertura por indicador</h2><p>Campos cuantitativos capturados / espacios de captura de la plantilla</p></div><span className="legend"><i/>Capturado <i className="pending"/>Pendiente</span></div><div className="indicator-grid">{indicators.map(id => { const c = coverage(groups, schema, id); const amount = groups.filter(g => g.section.indicators.includes(id)).length; const name = schema.indicators?.find(i => i.id === id)?.label ?? `Indicador ${id}`; return <button key={id} title={name} className="indicator-tile" onClick={() => onIndicator(id)}><div><span>Indicador {String(id).padStart(2, '0')}</span><ArrowUpRight size={14}/></div><strong>{c.percentage}<small>%</small></strong><span className="meter"><span style={{ width: `${c.percentage}%` }}/></span><small>{amount} registros · {c.filled}/{c.expected} campos</small></button>; })}</div></section>
    <div className="two-columns"><Bars title="Aportaciones por fuente" subtitle="Registros en el consolidado por origen" items={sources.map(s => ({ id: s.id, label: s.name, value: groups.filter(g => g.sourceIds.includes(s.id)).length })).sort((a, b) => b.value - a.value)} onSelect={onSource}/><Bars title="Distribución por indicador" subtitle="Un anexo puede aportar a varios indicadores" items={indicators.map(id => ({ id: String(id), label: `Indicador ${String(id).padStart(2, '0')}`, value: groups.filter(g => g.section.indicators.includes(id)).length })).filter(i => i.value > 0)} onSelect={id => onIndicator(Number(id))}/></div>
  </>;
}
