import { useRef, useState } from 'react';
import { FileSpreadsheet, Upload, X } from 'lucide-react';
import { Dialog } from './Dialog';
export function ImportDialog({ onClose, onImport }: { onClose: () => void; onImport: (items: { file: File; name: string }[]) => void }) {
  const [items, setItems] = useState<{ file: File; name: string }[]>([]); const input = useRef<HTMLInputElement>(null); const [error, setError] = useState('');
  function add(files: File[]) { const valid = files.filter(f => /\.xlsx$/i.test(f.name)); if (valid.length !== files.length) setError('Sólo se admiten archivos .xlsx.'); setItems(previous => [...previous, ...valid.map(file => ({ file, name: file.name.replace(/\.xlsx$/i, '').slice(0, 45) }))]); }
  return <Dialog title="Importar archivos Excel" onClose={onClose}><form onSubmit={e => { e.preventDefault(); if (items.length && items.every(i => i.name.trim())) onImport(items.map(i => ({ ...i, name: i.name.trim() }))); }}>
    <div className="dialog-body"><button type="button" className="dropzone" onDragOver={e => e.preventDefault()} onDrop={e => { e.preventDefault(); add([...e.dataTransfer.files]); }} onClick={() => input.current?.click()}><Upload size={28}/><strong>Seleccionar o arrastrar archivos</strong><span>Plantilla de captura CAI 2026 · .xlsx · varios archivos</span></button><input ref={input} type="file" multiple accept=".xlsx" hidden onChange={e => { add([...e.target.files ?? []]); e.target.value = ''; }}/>
    <div className="import-items">{items.map((item, i) => <div key={i} className="import-item"><FileSpreadsheet size={22}/><div><strong title={item.file.name}>{item.file.name}</strong><label>Nombre corto interno<input aria-label={`Nombre corto de ${item.file.name}`} maxLength={60} required value={item.name} onChange={e => setItems(items.map((v, index) => index === i ? { ...v, name: e.target.value } : v))}/></label></div><button type="button" className="icon-button" aria-label={`Quitar ${item.file.name}`} onClick={() => setItems(items.filter((_, index) => index !== i))}><X size={16}/></button></div>)}</div>{error && <p className="error-message">{error}</p>}
    </div><div className="dialog-footer"><span className="muted">Procesamiento local en este navegador</span><button type="button" className="button secondary" onClick={onClose}>Cancelar</button><button disabled={!items.length} className="button primary">Importar{items.length ? ` ${items.length} archivo${items.length === 1 ? '' : 's'}` : ''}</button></div>
  </form></Dialog>;
}
