import type { RecordGroup, WorkbookSchema } from '../models/types';
import { coverage, fieldCount } from '../services/consolidation';
export function IndicatorsView({ schema, groups, onSelect, criteria = false }: { schema: WorkbookSchema; groups: RecordGroup[]; onSelect: (id: string) => void; criteria?: boolean }) {
  return <section className="panel"><div className="panel-heading"><div><h2>{criteria ? 'Criterios transversales' : 'Indicadores SEAES'}</h2><p>Definiciones y campos tomados del formulario oficial CAI 2026</p></div></div><div className="catalog-list">{(criteria ? schema.criteria.map(c => ({ id: c.id, label: c.label })) : (schema.indicators ?? Array.from({ length: 20 }, (_, i) => ({ id: i + 1, label: `Indicador ${i + 1}` }))).map(i => ({ ...i, id: String(i.id) }))).map(item => {
    const c = coverage(groups, schema, criteria ? undefined : Number(item.id), criteria ? item.id : undefined);
    const rows = groups.filter(g => criteria ? g.section.fields.some(f => f.criterion === item.id && g.resolved.values[f.id] !== undefined) : g.section.indicators.includes(Number(item.id)));
    const sources = new Set(rows.flatMap(g => g.sourceIds));
    return <article key={item.id} className="catalog-item"><span className="catalog-number">{criteria ? schema.criteria.findIndex(v => v.id === item.id) + 1 : String(item.id).padStart(2, '0')}</span><div><button className="catalog-title" onClick={() => onSelect(item.id)}>{item.label}</button><div className="catalog-meta"><span>{rows.length} registros</span><span>{sources.size} fuentes</span><span>{rows.reduce((n, g) => n + fieldCount(g.resolved), 0)} campos capturados</span><span>{rows.filter(g => g.status === 'conflict').length} conflictos</span></div>{!criteria && <details><summary>Definición y periodo</summary><p>{schema.indicators?.find(i => i.id === Number(item.id))?.description}</p><p>{schema.indicators?.find(i => i.id === Number(item.id))?.period}</p></details>}</div><div className="coverage-cell"><strong>{c.percentage}%</strong><span className="meter"><span style={{ width: `${c.percentage}%` }}/></span><small>{c.filled}/{c.expected} campos cuantitativos</small><button className="button text small" onClick={() => onSelect(item.id)}>Consultar registros</button></div></article>;
  })}</div></section>;
}
