import type { DataSource, RecordGroup, SeaesRecord } from '../models/types';
import { Dialog } from './Dialog';
import { hasValue, recordLabel } from '../services/consolidation';
export function RecordDetail({ group, sources, onClose, onEdit, onDelete }: { group: RecordGroup; sources: DataSource[]; onClose: () => void; onEdit: (r: SeaesRecord) => void; onDelete: (r: SeaesRecord) => void }) {
  return <Dialog title={recordLabel(group.resolved, group.section)} onClose={onClose} wide><div className="dialog-body"><p className="eyebrow">{group.section.label}</p>
    {group.records.map(record => { const source = sources.find(s => s.id === record.sourceId); return <section key={record.id} className="provenance-block"><div className="panel-heading"><h3>{source?.name ?? 'Origen'}</h3><div className="button-row"><button className="button secondary small" onClick={() => onEdit(record)}>Editar</button><button className="button danger small" onClick={() => onDelete(record)}>Eliminar</button></div></div><p className="muted">{source?.filename} · {source?.kind === 'demo' ? 'Datos ficticios · ' : ''}{source?.importedAt && new Date(source.importedAt).toLocaleString('es-MX')}{record.modifiedAt && ' · Modificado en el sitio'}</p>
      <div className="detail-table"><table><thead><tr><th>Campo</th><th>Valor actual</th><th>Celda de origen</th>{record.modifiedAt && <th>Valor original</th>}</tr></thead><tbody>{group.section.fields.filter(f => hasValue(record.values[f.id]) || hasValue(record.originalValues[f.id])).map(field => <tr key={field.id}><th>{field.label}</th><td className={record.values[field.id] !== record.originalValues[field.id] ? 'changed' : ''}>{String(record.values[field.id] ?? '—')}</td><td>{record.origins[field.id]?.sheet ?? 'Captura manual'}<small>{record.origins[field.id]?.cell}</small></td>{record.modifiedAt && <td>{String(record.originalValues[field.id] ?? '—')}</td>}</tr>)}</tbody></table></div>
    </section>; })}</div><div className="dialog-footer"><span className="muted">ID interno: {group.resolved.id}</span><button className="button secondary" onClick={onClose}>Cerrar</button></div></Dialog>;
}
