import { useEffect, useState } from 'react';
import { ChevronLeft, ChevronRight, Columns3, Eye, Pencil, Trash2, ArrowDownUp } from 'lucide-react';
import type { DataSource, RecordGroup, SeaesRecord } from '../models/types';
import { fieldCount, hasValue, recordLabel } from '../services/consolidation';
export const statusText: Record<RecordGroup['status'], string> = { unique: 'Único', exact: 'Duplicado exacto', possible: 'Posible coincidencia', complementary: 'Complementario', conflict: 'Conflicto' };
export function RecordsTable({ groups, sources, onDetail, onEdit, onDelete }: { groups: RecordGroup[]; sources: DataSource[]; onDetail: (g: RecordGroup) => void; onEdit: (r: SeaesRecord) => void; onDelete: (records: SeaesRecord[]) => void }) {
  const [page, setPage] = useState(0); const [sort, setSort] = useState<'section' | 'name' | 'fields'>('section'); const [showColumns, setShowColumns] = useState(false); const [hidden, setHidden] = useState<string[]>([]); const [selected, setSelected] = useState<Set<string>>(new Set());
  useEffect(() => { setPage(0); setSelected(new Set()); }, [groups]);
  const sorted = [...groups].sort((a, b) => sort === 'name' ? recordLabel(a.resolved, a.section).localeCompare(recordLabel(b.resolved, b.section), 'es') : sort === 'fields' ? fieldCount(b.resolved) - fieldCount(a.resolved) : a.section.indicators[0] - b.section.indicators[0]);
  const pages = Math.max(1, Math.ceil(sorted.length / 25)); const current = sorted.slice(Math.min(page, pages - 1) * 25, (Math.min(page, pages - 1) + 1) * 25);
  const visible = (name: string) => !hidden.includes(name);
  function toggle(id: string) { setSelected(prev => { const next = new Set(prev); next.has(id) ? next.delete(id) : next.add(id); return next; }); }
  return <section className="panel records-panel"><div className="table-toolbar"><h2>{groups.length.toLocaleString('es-MX')} registros</h2><div className="button-row">{!!selected.size && <button className="button danger small" onClick={() => onDelete(groups.filter(g => selected.has(g.id)).flatMap(g => g.records))}><Trash2 size={15}/>Eliminar {selected.size}</button>}<label className="sort-control"><ArrowDownUp size={15}/><select aria-label="Ordenar registros" value={sort} onChange={e => setSort(e.target.value as typeof sort)}><option value="section">Por indicador</option><option value="name">Por nombre</option><option value="fields">Por campos capturados</option></select></label><button className="button secondary small" onClick={() => setShowColumns(!showColumns)}><Columns3 size={15}/>Columnas</button></div></div>
    {showColumns && <div className="column-options">{['Contenido', 'Fuentes', 'Campos', 'Estado'].map(name => <label key={name}><input type="checkbox" checked={visible(name)} onChange={() => setHidden(visible(name) ? [...hidden, name] : hidden.filter(n => n !== name))}/>{name}</label>)}</div>}
    <div className="table-scroll"><table className="records-table"><thead><tr><th className="checkbox-cell"><input type="checkbox" aria-label="Seleccionar página" checked={!!current.length && current.every(g => selected.has(g.id))} onChange={e => setSelected(e.target.checked ? new Set([...selected, ...current.map(g => g.id)]) : new Set([...selected].filter(id => !current.some(g => g.id === id))))}/></th><th>Registro / indicador</th>{visible('Contenido') && <th>Contenido capturado</th>}{visible('Fuentes') && <th>Fuentes</th>}{visible('Campos') && <th>Campos</th>}{visible('Estado') && <th>Estado</th>}<th className="actions-cell">Acciones</th></tr></thead><tbody>{current.map(group => <tr key={group.id} className={selected.has(group.id) ? 'selected' : ''}><td className="checkbox-cell"><input type="checkbox" checked={selected.has(group.id)} aria-label={`Seleccionar ${recordLabel(group.resolved, group.section)}`} onChange={() => toggle(group.id)}/></td><td><button className="record-title" onClick={() => onDetail(group)} title={recordLabel(group.resolved, group.section)}>{recordLabel(group.resolved, group.section)}</button><small className="cell-subtitle" title={group.section.label}>{group.section.label}</small></td>{visible('Contenido') && <td><div className="value-preview">{group.section.fields.filter(f => hasValue(group.resolved.values[f.id])).slice(0, 3).map(f => <span key={f.id} title={`${f.label}: ${group.resolved.values[f.id]}`}><span>{f.label}: </span>{String(group.resolved.values[f.id])}</span>)}</div></td>}{visible('Fuentes') && <td><div className="source-tags">{group.sourceIds.slice(0, 2).map(id => { const source = sources.find(s => s.id === id); return <span key={id} className="source-tag" title={source?.filename}>{source?.name}{source?.kind === 'demo' && <sup> F</sup>}</span>; })}{group.sourceIds.length > 2 && <span className="source-tag">+{group.sourceIds.length - 2}</span>}</div></td>}{visible('Campos') && <td><span className="tabular">{fieldCount(group.resolved)}/{group.section.fields.length}</span></td>}{visible('Estado') && <td><span className={`badge ${group.status}`}>{group.status === 'conflict' && group.conflicts.every(c => c.resolved) ? 'Resuelto' : statusText[group.status]}</span></td>}<td><div className="button-row"><button className="icon-button" aria-label={`Ver ${recordLabel(group.resolved, group.section)}`} onClick={() => onDetail(group)}><Eye size={17}/></button><button className="icon-button" aria-label={`Editar ${recordLabel(group.resolved, group.section)}`} onClick={() => onEdit(group.records[0])}><Pencil size={16}/></button></div></td></tr>)}</tbody></table>{!current.length && <div className="quiet-empty">No hay registros que coincidan con los filtros.</div>}</div>
    <div className="table-footer"><span>{groups.length ? page * 25 + 1 : 0}–{Math.min((page + 1) * 25, groups.length)} de {groups.length} registros</span><div className="button-row"><button className="icon-button" disabled={!page} aria-label="Página anterior" onClick={() => setPage(page - 1)}><ChevronLeft size={18}/></button><span>Página {page + 1} de {pages}</span><button className="icon-button" disabled={page >= pages - 1} aria-label="Página siguiente" onClick={() => setPage(page + 1)}><ChevronRight size={18}/></button></div></div>
  </section>;
}
