import { useState } from 'react';
import { Download } from 'lucide-react';
import { Dialog } from '../../components/Dialog';
import type { ExportReport } from '../../models/types';

export function ExportDialog({ initialMode, records, sources, demoSources, pending, onClose, onReview, onExport }: { initialMode: 'full' | 'simplified'; records: number; sources: number; demoSources: number; pending: number; onClose: () => void; onReview: () => void; onExport: (mode: 'full' | 'simplified') => void }) {
  const [mode, setMode] = useState(initialMode);
  return <Dialog title="Exportar Excel" onClose={onClose}><div className="dialog-body"><div className="export-options"><label className={mode === 'full' ? 'selected' : ''}><input type="radio" name="export-mode" checked={mode === 'full'} onChange={() => setMode('full')}/><span><strong>Excel completo</strong><small>Mantiene toda la plantilla</small></span></label><label className={mode === 'simplified' ? 'selected' : ''}><input type="radio" name="export-mode" checked={mode === 'simplified'} onChange={() => setMode('simplified')}/><span><strong>Excel simplificado</strong><small>Solo información relevante y hojas necesarias</small></span></label></div><p className="export-scope">Todo el consolidado: <strong>{records} registros · {sources} fuentes</strong></p>{demoSources > 0 && <p className="message warning">Incluye {demoSources} fuentes ficticias.</p>}{pending > 0 && <p className="message warning">{pending} registros con conflictos pendientes. Los campos sin decisión usarán la primera aportación.</p>}</div><div className="dialog-footer">{pending > 0 && <button className="button secondary" onClick={onReview}>Revisar conflictos</button>}<button className="button primary" onClick={() => onExport(mode)}><Download size={17}/>Exportar</button></div></Dialog>;
}

export function ExportResult({ report, onClose }: { report: ExportReport; onClose: () => void }) {
  const omitted = Array.isArray(report.removedSheets) ? report.removedSheets as string[] : [];
  const retained = Array.isArray(report.retainedDependencySheets) ? report.retainedDependencySheets as string[] : [];
  return <Dialog title="Excel generado" onClose={onClose}><div className="dialog-body"><div className="detail-metrics"><div><strong>{report.sheets}</strong><span>hojas</span></div><div><strong>{report.changedCells}</strong><span>celdas actualizadas</span></div></div><details className="compact-disclosure"><summary>Verificación del archivo</summary><dl className="verification-list"><div><dt>Fórmulas</dt><dd>{report.formulas}</dd></div><div><dt>Gráficas</dt><dd>{report.charts}</dd></div><div><dt>Partes sin cambios</dt><dd>{report.preservedParts}</dd></div></dl></details>{omitted.length > 0 && <details className="compact-disclosure"><summary>{omitted.length} hojas omitidas</summary><ul>{omitted.map(s => <li key={s}>{s}</li>)}</ul></details>}{retained.length > 0 && <details className="compact-disclosure"><summary>{retained.length} hojas conservadas por dependencias</summary><ul>{retained.map(s => <li key={s}>{s}</li>)}</ul></details>}{report.warnings.length > 0 && <details className="compact-disclosure"><summary>{report.warnings.length} observaciones</summary><ul>{report.warnings.map((w, i) => <li key={i}>{w}</li>)}</ul></details>}</div><div className="dialog-footer"><button className="button primary" onClick={onClose}>Cerrar</button></div></Dialog>;
}
