import { useEffect, useMemo, useState } from 'react';
import { ChevronDown, FlaskConical, MoreHorizontal, Upload, Download, Trash2 } from 'lucide-react';
import { ExcelIcon } from '../../components/ExcelIcon';
import type { DataSource, RecordGroup, WorkbookSchema } from '../../models/types';
import { coverage } from '../../services/consolidation';
import { Dialog } from '../../components/Dialog';
import { SearchField } from '../../components/SearchField';

const compatibility = { compatible: 'Compatible', variations: 'Con variaciones', partial: 'Parcial', unknown: 'Error de lectura' };
interface Props { schema: WorkbookSchema; sources: DataSource[]; groups: RecordGroup[]; busy: string; onImport: () => void; onDemo: () => void; onExport: (mode: 'full' | 'simplified') => void; onRecords: (sourceId: string) => void; onDelete: (source: DataSource) => void; onRemoveDemo: () => void; onClear: () => void }
export function FilesScreen({ schema, sources, groups, busy, onImport, onDemo, onExport, onRecords, onDelete, onRemoveDemo, onClear }: Props) {
  const [selectedId, setSelectedId] = useState<string>(); const [query, setQuery] = useState(''); const [page, setPage] = useState(0);
  const selected = sources.find(s => s.id === selectedId);
  const visible = useMemo(() => sources.filter(s => `${s.name} ${s.filename}`.toLocaleLowerCase('es-MX').includes(query.toLocaleLowerCase('es-MX'))), [sources, query]);
  const demo = sources.filter(s => s.kind === 'demo'); const pages = Math.max(1, Math.ceil(visible.length / 20));
  useEffect(() => setPage(0), [query]); useEffect(() => setPage(p => Math.min(p, pages - 1)), [pages]);
  const own = selected ? groups.filter(g => g.sourceIds.includes(selected.id)) : [];
  const sourceGroups = selected ? own.map(g => ({ ...g, resolved: { ...g.resolved, values: Object.assign({}, ...g.records.filter(r => r.sourceId === selected.id).map(r => r.values)) } })) : [];
  const c = coverage(sourceGroups, schema);
  const sourceButton = (s: DataSource) => <button className="record-title source-title" onClick={() => setSelectedId(s.id)}><ExcelIcon size={29}/><span>{s.name}</span></button>;
  return <><div className="screen-actions"><div className="button-row"><button className="button primary" disabled={!!busy} onClick={onImport}><Upload size={17}/>Importar Excel</button><button className="button secondary" disabled={!!busy || !!demo.length} onClick={onDemo}><FlaskConical size={17}/>Usar datos ficticios</button><details className="action-menu"><summary className="button secondary" aria-label="Opciones de exportación"><Download size={17}/>Exportar<ChevronDown size={15}/></summary><div className="menu-content"><button disabled={!!busy} onClick={e => { e.currentTarget.closest('details')?.removeAttribute('open'); onExport('full'); }}>Excel completo</button><button disabled={!!busy} onClick={e => { e.currentTarget.closest('details')?.removeAttribute('open'); onExport('simplified'); }}>Excel simplificado</button></div></details></div><details className="action-menu"><summary className="icon-button" aria-label="Más acciones de archivos" title="Más acciones"><MoreHorizontal size={21}/></summary><div className="menu-content align-right">{!!demo.length && <button disabled={!!busy} onClick={e => { e.currentTarget.closest('details')?.removeAttribute('open'); onRemoveDemo(); }}>Eliminar datos ficticios</button>}<button className="danger-text" disabled={!!busy || !sources.length} onClick={e => { e.currentTarget.closest('details')?.removeAttribute('open'); onClear(); }}>Limpiar sesión</button></div></details></div>
  <section className="panel files-panel"><div className="panel-heading"><div className="button-row"><h2 className="sources-heading"><ExcelIcon size={27}/>Fuentes</h2><span className="count">{sources.length}</span>{!!demo.length && <span className="badge demo">Datos ficticios</span>}</div><SearchField value={query} onChange={setQuery} label="Buscar archivos" placeholder="Buscar fuente o archivo…"/></div><div className="table-scroll"><table className="files-table"><thead><tr><th>Fuente</th><th>Registros</th><th>Indicadores</th><th>Estado</th><th>Fecha</th></tr></thead><tbody>{visible.slice(page * 20, (page + 1) * 20).map(s => { const contributed = groups.filter(g => g.sourceIds.includes(s.id)); return <tr key={s.id}><td>{sourceButton(s)}<small className="cell-subtitle">{s.filename}</small></td><td>{contributed.length.toLocaleString('es-MX')}</td><td>{new Set(contributed.flatMap(g => g.section.indicators)).size}</td><td><span className={`badge ${s.compatibility === 'unknown' ? 'conflict' : s.warnings.length ? 'possible' : 'unique'}`}>{s.warnings.length ? `${s.warnings.length} advertencia${s.warnings.length === 1 ? '' : 's'}` : compatibility[s.compatibility]}</span>{s.kind === 'demo' && <span className="badge demo">Ficticio</span>}{s.kind === 'manual' && <span className="badge">Manual</span>}</td><td>{new Date(s.importedAt).toLocaleDateString('es-MX')}</td></tr>; })}</tbody></table>{!visible.length && <div className="quiet-empty">{query ? 'No hay archivos que coincidan.' : 'No hay fuentes cargadas.'}</div>}</div><div className="table-footer"><span>{visible.length ? page * 20 + 1 : 0}–{Math.min((page + 1) * 20, visible.length)} de {visible.length} fuentes</span><div className="button-row"><button className="button text small" disabled={!page} onClick={() => setPage(page - 1)}>Anterior</button><span>{page + 1} / {pages}</span><button className="button text small" disabled={page >= pages - 1} onClick={() => setPage(page + 1)}>Siguiente</button></div></div></section>
  {selected && <Dialog title={selected.name} onClose={() => setSelectedId(undefined)} drawer wide><div className="dialog-body"><div className="detail-metrics"><div><strong>{own.length}</strong><span>registros</span></div><div><strong>{new Set(own.flatMap(g => g.section.indicators)).size}</strong><span>indicadores</span></div><div><strong>{c.percentage}%</strong><span>cobertura aportada</span></div></div><dl className="verification-list"><div><dt>Archivo original</dt><dd>{selected.filename}</dd></div><div><dt>Fecha de importación</dt><dd>{new Date(selected.importedAt).toLocaleString('es-MX')}</dd></div><div><dt>Compatibilidad</dt><dd>{compatibility[selected.compatibility]}</dd></div><div><dt>Conflictos pendientes</dt><dd>{own.filter(g => g.conflicts.some(v => !v.resolved)).length}</dd></div><div><dt>Duplicados / coincidencias</dt><dd>{own.filter(g => ['exact', 'possible'].includes(g.status)).length}</dd></div><div><dt>Campos cuantitativos capturados</dt><dd>{c.filled} / {c.expected}</dd></div></dl><details className="compact-disclosure"><summary>Indicadores y hojas</summary><p>{[...new Set(own.flatMap(g => g.section.indicators))].sort((a, b) => a - b).map(i => String(i).padStart(2, '0')).join(' · ') || 'Sin información'}</p><ul>{[...new Set(own.map(g => g.section.sheet))].map(sheet => <li key={sheet}>{sheet}</li>)}</ul></details>{!!selected.warnings.length && <details className="compact-disclosure"><summary>{selected.warnings.length} advertencias</summary><ul>{selected.warnings.map((w, i) => <li key={i}>{w}</li>)}</ul></details>}</div><div className="dialog-footer"><button className="button danger" disabled={!!busy} onClick={() => onDelete(selected)}><Trash2 size={16}/>Eliminar fuente</button><button className="button primary" onClick={() => { onRecords(selected.id); setSelectedId(undefined); }}>Ver registros</button></div></Dialog>}</>;
}
