import { Filter, X } from 'lucide-react';
import { useState } from 'react';
import type { DataSource, WorkbookSchema } from '../../models/types';
import { Dialog } from '../../components/Dialog';
import { cleanFilters, type Filters } from './filters';

export function RecordFilters({ schema, sources, filters, onChange }: { schema: WorkbookSchema; sources: DataSource[]; filters: Filters; onChange: (value: Filters) => void }) {
  const [advanced, setAdvanced] = useState(false);
  const set = (key: keyof Filters, value: string) => onChange({ ...filters, [key]: value, groupIds: undefined });
  const active = Object.entries(filters).filter(([, v]) => Array.isArray(v) ? true : !!v).length;
  return <><div className="record-filters"><select aria-label="Filtrar por indicador" value={filters.indicator} onChange={e => set('indicator', e.target.value)}><option value="">Todos los indicadores</option>{schema.indicators?.map(i => <option key={i.id} value={i.id}>Indicador {String(i.id).padStart(2, '0')}</option>)}</select><select aria-label="Filtrar por origen" value={filters.source} onChange={e => set('source', e.target.value)}><option value="">Todos los orígenes</option>{sources.map(s => <option key={s.id} value={s.id}>{s.name}</option>)}</select><select aria-label="Filtrar por estado" value={filters.status} onChange={e => set('status', e.target.value)}><option value="">Todos los estados</option><option value="unique">Únicos</option><option value="duplicates">Duplicados</option><option value="conflicts">Conflictos</option><option value="pending">Conflictos pendientes</option><option value="complementary">Complementarios</option><option value="exact">Duplicados exactos</option><option value="possible">Posibles coincidencias</option></select><button className="button secondary small" onClick={() => setAdvanced(true)}><Filter size={15}/>Filtros{active > 0 && <span className="count">{active}</span>}</button>{active > 0 && <button className="button text small" onClick={() => onChange({ ...cleanFilters })}><X size={15}/>Restablecer</button>}</div>
  {advanced && <Dialog title="Filtros de registros" onClose={() => setAdvanced(false)}><div className="dialog-body filter-grid"><label>Criterio SEAES<select value={filters.criterion} onChange={e => set('criterion', e.target.value)}><option value="">Todos los criterios</option>{schema.criteria.map(c => <option key={c.id} value={c.id}>{c.label}</option>)}</select></label><label>Hoja / sección<select value={filters.section} onChange={e => set('section', e.target.value)}><option value="">Todas las secciones</option>{schema.sections.map(s => <option key={s.id} value={s.id}>{s.sheet} · {s.label}</option>)}</select></label><label>Tipo de origen<select value={filters.kind} onChange={e => set('kind', e.target.value)}><option value="">Todos los orígenes</option><option value="real">Archivos reales</option><option value="demo">Datos ficticios</option><option value="manual">Captura manual</option></select></label><label>Completitud<select value={filters.completeness} onChange={e => set('completeness', e.target.value)}><option value="">Todos</option><option value="complete">Campos completos</option><option value="partial">Campos pendientes</option></select></label><label>Programa educativo<input value={filters.programme} onChange={e => set('programme', e.target.value)}/></label><label>Periodo<input value={filters.period} onChange={e => set('period', e.target.value)}/></label></div><div className="dialog-footer"><button className="button text" onClick={() => onChange({ ...cleanFilters })}>Restablecer</button><button className="button primary" onClick={() => setAdvanced(false)}>Ver resultados</button></div></Dialog>}</>;
}
