import { useEffect, useMemo, useState } from 'react';
import { BarChart3, LayoutDashboard, Rows3, ScanLine, GitCompareArrows, Files, Search, Upload, Download, Plus, FlaskConical, ShieldCheck, Trash2, X, Filter, BookOpen, ChevronDown, LoaderCircle, CheckCircle2, Menu, SlidersHorizontal } from 'lucide-react';
import type { RecordGroup, SeaesRecord } from './models/types';
import { consolidate, coverage, fieldCount, hasValue, normalize, recordLabel } from './services/consolidation';
import { useWorkspace } from './hooks/useWorkspace';
import { Dashboard, Stats, Bars } from './components/Dashboard';
import { RecordsTable } from './components/RecordsTable';
import { IndicatorsView } from './components/IndicatorsView';
import { AuditView } from './components/AuditView';
import { Dialog } from './components/Dialog';
import { ImportDialog } from './components/ImportDialog';
import { RecordEditor } from './components/RecordEditor';
import { RecordDetail } from './components/RecordDetail';

type View = 'overview' | 'records' | 'indicators' | 'criteria' | 'audit' | 'statistics';
interface Filters { source: string; indicator: string; criterion: string; section: string; kind: string; status: string; completeness: string; programme: string; period: string }
const cleanFilters: Filters = { source: '', indicator: '', criterion: '', section: '', kind: '', status: '', completeness: '', programme: '', period: '' };
const filterKey = `seaes-filters:${location.pathname}`;
const nav = [ { id: 'overview', label: 'Vista general', icon: LayoutDashboard }, { id: 'records', label: 'Consolidado', icon: Rows3 }, { id: 'indicators', label: 'Indicadores', icon: BarChart3 }, { id: 'criteria', label: 'Criterios SEAES', icon: ScanLine }, { id: 'audit', label: 'Revisión de datos', icon: GitCompareArrows }, { id: 'statistics', label: 'Estadísticas', icon: SlidersHorizontal } ] as const;
const compatibilityLabels = { compatible: 'Compatible', variations: 'Compatible con variaciones', partial: 'Parcialmente compatible', unknown: 'Error de lectura' };

export function App() {
  const workspace = useWorkspace(); const { schema, session, busy, ready, error, notice } = workspace;
  const [view, setView] = useState<View>('overview'); const [query, setQuery] = useState('');
  const [filters, setFilters] = useState<Filters>(() => { try { return { ...cleanFilters, ...JSON.parse(localStorage.getItem(filterKey) ?? '{}') }; } catch { return cleanFilters; } });
  const [advanced, setAdvanced] = useState(false); const [sidebar, setSidebar] = useState(false); const [importing, setImporting] = useState(false);
  const [editor, setEditor] = useState<{ record?: SeaesRecord }>(); const [detail, setDetail] = useState<RecordGroup>(); const [references, setReferences] = useState(false);
  const [referenceName, setReferenceName] = useState(''); const [exporting, setExporting] = useState(false);
  const [confirmation, setConfirmation] = useState<{ title: string; text: string; action: () => void }>();
  useEffect(() => { try { localStorage.setItem(filterKey, JSON.stringify(filters)); } catch { /* Persistence failure is reported by session storage. */ } }, [filters]);
  const groups = useMemo(() => schema ? consolidate(session.records, schema, session.decisions) : [], [schema, session.records, session.decisions]);
  const selectedSource = session.sources.find(s => s.id === filters.source);
  const scopedGroups = useMemo(() => !schema ? [] : consolidate(session.records.filter(r => (!filters.source || r.sourceId === filters.source) && (!filters.kind || session.sources.find(s => s.id === r.sourceId)?.kind === filters.kind)), schema, session.decisions), [session, schema, filters.source, filters.kind]);
  const filtered = useMemo(() => scopedGroups.filter(g => {
    if (filters.indicator && !g.section.indicators.includes(Number(filters.indicator))) return false;
    if (filters.criterion && !g.section.fields.some(f => f.criterion === filters.criterion && hasValue(g.resolved.values[f.id]))) return false;
    if (filters.section && g.section.id !== filters.section) return false;
    if (filters.status === 'pending' ? !g.conflicts.some(c => !c.resolved) : filters.status && g.status !== filters.status) return false;
    const expected = g.section.fields.filter(f => g.section.rows.find(row => row.id === g.resolved.rowId)?.fields[f.id]).length;
    if (filters.completeness === 'complete' && fieldCount(g.resolved) < expected || filters.completeness === 'partial' && fieldCount(g.resolved) >= expected) return false;
    const values = Object.values(g.resolved.values).map(normalize).join(' ');
    if (filters.programme && !values.includes(normalize(filters.programme)) || filters.period && !values.includes(normalize(filters.period))) return false;
    if (!query.trim()) return true;
    const text = normalize([recordLabel(g.resolved, g.section), g.section.sheet, g.section.label, ...Object.values(g.resolved.values), ...g.section.fields.map(f => f.label), ...g.sourceIds.flatMap(id => { const source = session.sources.find(s => s.id === id); return [source?.name, source?.filename]; }), ...g.section.indicators.map(i => schema?.indicators?.find(v => v.id === i)?.label), ...g.section.fields.filter(f => f.criterion && hasValue(g.resolved.values[f.id])).map(f => schema?.criteria.find(c => c.id === f.criterion)?.label)].join(' '));
    return normalize(query).split(' ').every(word => text.includes(word));
  }), [scopedGroups, filters, query, schema, session.sources]);
  const filteredSources = session.sources.filter(s => (!filters.source || s.id === filters.source) && (!filters.kind || s.kind === filters.kind));
  const demoSources = session.sources.filter(s => s.kind === 'demo'); const pending = groups.filter(g => g.conflicts.some(c => !c.resolved)).length;
  const programmes = useMemo(() => [...new Set(groups.filter(g => g.section.kind === 'annex').flatMap(g => g.section.fields.filter(f => /programa|origen/i.test(f.label) && f.type === 'text').map(f => String(g.resolved.values[f.id] ?? '')).filter(v => v && v.length < 180)))].sort(), [groups]);
  const periods = useMemo(() => [...new Set(groups.flatMap(g => g.section.fields.filter(f => /periodo|cohorte/i.test(f.label)).map(f => String(g.resolved.values[f.id] ?? '')).filter(v => v && v.length < 100)))].sort(), [groups]);
  const filter = (name: keyof Filters, value: string) => setFilters(previous => ({ ...previous, [name]: value }));
  const openIndicator = (id: number) => { setFilters({ ...cleanFilters, source: filters.source, indicator: String(id) }); setView('records'); };
  const openSource = (id: string) => { setFilters({ ...cleanFilters, source: id }); setSidebar(false); };
  const deleteRecords = (records: SeaesRecord[]) => setConfirmation({ title: 'Eliminar registros', text: `Se eliminarán ${records.length} aportaciones de esta sesión. Los archivos originales permanecen intactos.`, action: () => { workspace.deleteRecords(records); setDetail(undefined); } });
  const title = selectedSource ? selectedSource.name : nav.find(n => n.id === view)?.label;
  const resetFilters = () => { setFilters(cleanFilters); setQuery(''); };

  if (!schema || !ready) return <div className="loading-screen"><div className="brand-mark">UT</div>{busy && <LoaderCircle className="spin"/>}<h1>SEAES · UTSJR</h1><p role="status">{busy || error}</p>{!busy && <button className="button primary" onClick={() => location.reload()}>Volver a cargar</button>}</div>;
  return <div className="app-shell">
    <aside className={`sidebar ${sidebar ? 'open' : ''}`}><div className="brand"><div className="brand-mark">UT</div><div><strong>SEAES<span> / UTSJR</span></strong><small>Información institucional</small></div><button className="icon-button mobile-close" aria-label="Cerrar navegación" onClick={() => setSidebar(false)}><X size={20}/></button></div>
      <div className="sidebar-section-label">ESPACIO DE TRABAJO</div><nav aria-label="Principal">{nav.map(({ id, label, icon: Icon }) => <button key={id} className={`nav-item ${view === id ? 'active' : ''}`} onClick={() => { setView(id); setSidebar(false); }}><Icon size={19}/><span>{label}</span>{id === 'audit' && pending > 0 && <small>{pending}</small>}</button>)}</nav>
      <div className="sidebar-divider"/><div className="sidebar-section-label source-heading">FUENTES <span>{session.sources.length}</span><button className="icon-button" title="Importar fuentes" aria-label="Importar fuentes" onClick={() => setImporting(true)}><Plus size={17}/></button></div>
      <button className={`source-nav ${!filters.source ? 'active' : ''}`} onClick={() => openSource('')}><Files size={17}/><span>Todas las fuentes</span><small>{session.records.length}</small></button>
      <div className="source-list">{session.sources.map((s, index) => <button key={s.id} className={`source-nav ${filters.source === s.id ? 'active' : ''}`} title={`${s.name} · ${s.filename} · ${compatibilityLabels[s.compatibility]}`} onClick={() => openSource(s.id)}><span className={`source-initial color-${index % 5}`}>{s.name.slice(0, 2).toUpperCase()}</span><span>{s.name}{s.kind === 'demo' && <sup> F</sup>}</span><small>{session.records.filter(r => r.sourceId === s.id).length}</small></button>)}{!session.sources.length && <p className="sidebar-empty">Tus archivos aparecerán aquí.</p>}</div>
      <div className="sidebar-bottom"><button className="nav-item" onClick={() => setReferences(true)}><BookOpen size={18}/><span>Referencias del formulario</span></button><div className="local-state"><ShieldCheck size={17}/><div><strong>Datos en este navegador</strong><small>{workspace.saved ? 'Sesión guardada' : 'Guardando sesión…'}</small></div></div><button className="clear-session" disabled={!session.sources.length || !!busy} onClick={() => setConfirmation({ title: 'Limpiar sesión', text: 'Se eliminarán las fuentes, las capturas y las decisiones guardadas en este navegador.', action: () => { void workspace.clearSession(); resetFilters(); } })}><Trash2 size={14}/>Limpiar sesión</button></div>
    </aside>
    {sidebar && <button className="sidebar-backdrop" aria-label="Cerrar menú" onClick={() => setSidebar(false)}/>}
    <main><header className="topbar"><div className="topbar-left"><button className="icon-button mobile-menu" aria-label="Abrir menú" onClick={() => setSidebar(true)}><Menu size={21}/></button><span>Universidad Tecnológica de San Juan del Río</span><span className="cycle-tag">CAI 2026</span></div><div className="global-search"><Search size={17}/><input aria-label="Buscar en todo el consolidado" placeholder="Buscar programa, indicador, campo…" value={query} onChange={e => { setQuery(e.target.value); if (e.target.value) setView('records'); }}/>{query && <button className="icon-button" aria-label="Limpiar búsqueda" onClick={() => setQuery('')}><X size={15}/></button>}</div></header>
    <div className="workspace"><div className="page-heading"><div><div className="eyebrow">SEAES / {selectedSource ? 'APORTACIONES POR FUENTE' : 'CONSOLIDACIÓN 2026'}</div><h1>{title}{demoSources.length > 0 && <span className="badge demo">Datos ficticios</span>}</h1><p>{selectedSource ? `${selectedSource.filename} · ${compatibilityLabels[selectedSource.compatibility]}` : 'Consulta, captura y revisión de indicadores institucionales'}</p></div><div className="primary-actions"><button className="button secondary" disabled={!!busy} onClick={() => setImporting(true)}><Upload size={17}/>Importar Excel</button><button className="button primary" disabled={!!busy} onClick={() => setExporting(true)}><Download size={17}/>Exportar Excel consolidado</button></div></div>
    <div className="context-actions"><div className="button-row"><button className="button secondary small" disabled={!!busy} onClick={() => setEditor({})}><Plus size={16}/>Agregar registro</button><button className="button text small" disabled={!!busy || !!demoSources.length} onClick={() => { resetFilters(); void workspace.useDemo(); }}><FlaskConical size={16}/>Usar datos ficticios</button>{!!demoSources.length && <button className="button text small" disabled={!!busy} onClick={() => setConfirmation({ title: 'Quitar datos ficticios', text: 'Se eliminarán sólo las 14 fuentes ficticias y sus registros, incluidas sus ediciones. Se conservarán tus capturas manuales y archivos importados.', action: () => { void workspace.removeSources(demoSources.map(s => s.id)); resetFilters(); } })}>Quitar ficticios</button>}</div><span className="subtle">{session.sources.filter(s => s.kind !== 'manual').length} fuentes · {groups.length} registros consolidados</span></div>
    {busy && <div className="message processing" role="status"><LoaderCircle size={18} className="spin"/>{busy}</div>}{error && <div className="message error" role="alert"><span>{error}</span><button className="icon-button" aria-label="Cerrar error" onClick={() => workspace.setError('')}><X size={17}/></button></div>}{notice && <div className="message success" role="status"><CheckCircle2 size={18}/><span>{notice}</span><button className="icon-button" aria-label="Cerrar aviso" onClick={() => workspace.setNotice('')}><X size={17}/></button></div>}
    {selectedSource && <section className="source-context"><div><span className={`badge ${selectedSource.compatibility === 'unknown' ? 'conflict' : 'unique'}`}>{compatibilityLabels[selectedSource.compatibility]}</span><span>{scopedGroups.length} registros · {new Set(scopedGroups.map(g => g.section.sheet)).size} hojas · {new Set(scopedGroups.flatMap(g => g.section.indicators)).size} indicadores</span>{selectedSource.warnings.length > 0 && <details><summary>{selectedSource.warnings.length} observaciones de importación</summary>{selectedSource.warnings.map((w, i) => <p key={i}>{w}</p>)}</details>}</div><div className="button-row"><button className="button text small" onClick={() => openSource('')}>Ver todas</button><button className="button danger small" onClick={() => setConfirmation({ title: 'Eliminar fuente', text: `Se eliminarán la fuente «${selectedSource.name}» y sus aportaciones de la sesión.`, action: () => { void workspace.removeSources([selectedSource.id]); openSource(''); } })}><Trash2 size={15}/>Eliminar fuente</button></div></section>}
    <Stats groups={filtered} sources={filteredSources} schema={schema}/>
    <div className="filters"><Filter size={17}/><select aria-label="Filtrar por indicador" value={filters.indicator} onChange={e => filter('indicator', e.target.value)}><option value="">Todos los indicadores</option>{Array.from({ length: 20 }, (_, i) => <option key={i} value={i + 1}>Indicador {i + 1}</option>)}</select><select aria-label="Filtrar por criterio" value={filters.criterion} onChange={e => filter('criterion', e.target.value)}><option value="">Todos los criterios</option>{schema.criteria.map(c => <option value={c.id} key={c.id}>{c.label}</option>)}</select><select aria-label="Filtrar por estado" value={filters.status} onChange={e => filter('status', e.target.value)}><option value="">Todos los estados</option><option value="unique">Únicos</option><option value="exact">Duplicados exactos</option><option value="possible">Posibles coincidencias</option><option value="complementary">Complementarios</option><option value="conflict">Con diferencias</option><option value="pending">Conflictos pendientes</option></select><button className={`button text small ${advanced ? 'is-active' : ''}`} onClick={() => setAdvanced(!advanced)}>Más filtros<ChevronDown size={15}/></button>{(Object.values(filters).some(Boolean) || query) && <button className="button text small" onClick={resetFilters}><X size={14}/>Restablecer</button>}</div>
    {advanced && <div className="advanced-filters"><label>Hoja / sección<select value={filters.section} onChange={e => filter('section', e.target.value)}><option value="">Todas las secciones</option>{schema.sections.map(s => <option key={s.id} value={s.id}>{s.sheet} · {s.label}</option>)}</select></label><label>Tipo de origen<select value={filters.kind} onChange={e => filter('kind', e.target.value)}><option value="">Todos los orígenes</option><option value="real">Archivos reales</option><option value="demo">Datos ficticios</option><option value="manual">Captura manual</option></select></label><label>Completitud<select value={filters.completeness} onChange={e => filter('completeness', e.target.value)}><option value="">Todos</option><option value="complete">Campos completos</option><option value="partial">Campos pendientes</option></select></label><label>Programa / origen<input list="programmes" value={filters.programme} placeholder="Buscar programa" onChange={e => filter('programme', e.target.value)}/><datalist id="programmes">{programmes.map(p => <option key={p} value={p}/>)}</datalist></label><label>Periodo<input list="periods" value={filters.period} placeholder="Buscar periodo" onChange={e => filter('period', e.target.value)}/><datalist id="periods">{periods.map(p => <option key={p} value={p}/>)}</datalist></label></div>}
    {view === 'overview' && <Dashboard groups={filtered} sources={filteredSources} schema={schema} onIndicator={openIndicator} onSource={openSource} onImport={() => setImporting(true)} onAdd={() => setEditor({})} onDemo={() => void workspace.useDemo()} showEmpty={!session.sources.length}/>}
    {view === 'records' && <>{filters.indicator && <div className="indicator-context"><strong>{schema.indicators?.find(i => i.id === Number(filters.indicator))?.label}</strong><span>{coverage(filtered, schema, Number(filters.indicator)).missing} campos cuantitativos pendientes</span></div>}<RecordsTable groups={filtered} sources={session.sources} onDetail={setDetail} onEdit={record => setEditor({ record })} onDelete={deleteRecords}/></>}
    {(view === 'indicators' || view === 'criteria') && <IndicatorsView schema={schema} groups={filtered} criteria={view === 'criteria'} onSelect={id => { if (view === 'indicators') openIndicator(Number(id)); else { setFilters({ ...cleanFilters, source: filters.source, criterion: id }); setView('records'); } }}/ >}
    {view === 'audit' && <AuditView groups={filtered} sources={session.sources} decisions={session.decisions} onDecision={(id, decision) => workspace.setSession(s => ({ ...s, decisions: { ...s.decisions, [id]: decision } }))} onDetail={setDetail}/>}
    {view === 'statistics' && <><div className="two-columns"><Bars title="Registros por fuente" subtitle="Cada registro puede tener más de un origen" items={filteredSources.map(s => ({ id: s.id, label: s.name, value: filtered.filter(g => g.sourceIds.includes(s.id)).length }))} onSelect={openSource}/><Bars title="Campos por fuente" subtitle="Número de campos efectivamente capturados" items={filteredSources.map(s => ({ id: s.id, label: s.name, value: filtered.filter(g => g.sourceIds.includes(s.id)).reduce((n, g) => n + g.records.filter(r => r.sourceId === s.id).reduce((m, r) => m + fieldCount(r), 0), 0) }))}/></div><IndicatorsView schema={schema} groups={filtered} criteria onSelect={id => { filter('criterion', id); setView('records'); }}/><section className="panel source-comparison"><div className="panel-heading"><h2>Comparación de aportaciones</h2></div><div className="table-scroll"><table><thead><tr><th>Fuente</th><th>Registros</th><th>Hojas</th><th>Indicadores</th><th>Exclusivos</th><th>Coincidentes</th><th>Conflictos</th></tr></thead><tbody>{filteredSources.map(s => { const own = groups.filter(g => g.sourceIds.includes(s.id)); return <tr key={s.id}><td><button className="record-title" onClick={() => openSource(s.id)}>{s.name}</button></td><td>{own.length}</td><td>{new Set(own.map(g => g.section.sheet)).size}</td><td>{new Set(own.flatMap(g => g.section.indicators)).size}</td><td>{own.filter(g => g.sourceIds.length === 1).length}</td><td>{own.filter(g => g.sourceIds.length > 1).length}</td><td>{own.filter(g => g.conflicts.length).length}</td></tr>; })}</tbody></table></div></section></>}
    <footer className="workspace-footer"><span>SEAES · Universidad Tecnológica de San Juan del Río</span><span>Procesamiento local · Formulario CAI 2026</span></footer>
    </div></main>
    {importing && <ImportDialog onClose={() => setImporting(false)} onImport={items => { setImporting(false); void workspace.importFiles(items); }}/ >}
    {editor && <RecordEditor schema={schema} record={editor.record} onClose={() => setEditor(undefined)} onSave={data => { workspace.saveRecord(data, editor.record); setEditor(undefined); setDetail(undefined); }}/ >}
    {detail && <RecordDetail group={detail} sources={session.sources} onClose={() => setDetail(undefined)} onEdit={record => { setDetail(undefined); setEditor({ record }); }} onDelete={record => deleteRecords([record])}/>}
    {confirmation && <Dialog title={confirmation.title} onClose={() => setConfirmation(undefined)}><div className="dialog-body"><p>{confirmation.text}</p></div><div className="dialog-footer"><button className="button secondary" onClick={() => setConfirmation(undefined)}>Cancelar</button><button className="button danger solid" onClick={() => { confirmation.action(); setConfirmation(undefined); }}>Confirmar eliminación</button></div></Dialog>}
    {workspace.importSummary && <Dialog title="Resultado de la importación" onClose={() => workspace.setImportSummary(undefined)} wide><div className="dialog-body"><div className="table-scroll"><table><thead><tr><th>Fuente</th><th>Registros</th><th>Campos</th><th>Resultado</th></tr></thead><tbody>{workspace.importSummary.map(s => <tr key={s.id}><td>{s.name}</td><td>{s.records}</td><td>{s.fields}</td><td className="import-result">{s.message}</td></tr>)}</tbody></table></div></div><div className="dialog-footer"><button className="button primary" onClick={() => { workspace.setImportSummary(undefined); setView('records'); resetFilters(); }}>Ver consolidado</button></div></Dialog>}
    {references && <Dialog title="Referencias del formulario" onClose={() => setReferences(false)} wide><div className="dialog-body"><label>Documento de referencia<select value={referenceName || schema.referenceSheets?.[0]?.name} onChange={e => setReferenceName(e.target.value)}>{schema.referenceSheets?.map(r => <option key={r.name}>{r.name}</option>)}</select></label><div className="reference-text">{schema.referenceSheets?.find(r => r.name === (referenceName || schema.referenceSheets?.[0]?.name))?.text}</div></div><div className="dialog-footer"><span className="muted">Contenido original de la plantilla; no cuenta como aportación.</span><button className="button secondary" onClick={() => setReferences(false)}>Cerrar</button></div></Dialog>}
    {exporting && <Dialog title="Exportar Excel consolidado" onClose={() => setExporting(false)}><div className="dialog-body"><div className="export-summary"><div><strong>{groups.length}</strong><span>registros</span></div><div><strong>{session.sources.length}</strong><span>fuentes</span></div><div><strong>58</strong><span>hojas originales</span></div></div><p>Se exportará todo el consolidado, incluidos los registros que no aparecen con los filtros actuales.</p>{!!demoSources.length && <p className="message warning">Incluye datos ficticios de {demoSources.length} fuentes.</p>}{pending > 0 && <p className="message warning">Hay {pending} registros con conflictos pendientes. Se usará la primera aportación para cada campo sin resolver. Puedes revisarlos o exportar ahora.</p>}<p className="muted">Se verifican los datos insertados, las fórmulas, las gráficas y la estructura de la plantilla. Excel recalculará los resultados al abrir el archivo.</p></div><div className="dialog-footer">{pending > 0 && <button className="button secondary" onClick={() => { setExporting(false); setView('audit'); resetFilters(); }}>Revisar conflictos</button>}<button className="button primary" onClick={() => { setExporting(false); void workspace.download(); }}><Download size={17}/>Descargar Excel</button></div></Dialog>}
    {workspace.exportReport && <Dialog title="Excel generado y verificado" onClose={() => workspace.setExportReport(undefined)}><div className="dialog-body"><div className="export-success"><CheckCircle2 size={35}/><h3>Consolidado listo</h3></div><dl className="verification-list"><div><dt>Hojas conservadas</dt><dd>{workspace.exportReport.sheets}</dd></div><div><dt>Fórmulas conservadas</dt><dd>{workspace.exportReport.formulas}</dd></div><div><dt>Gráficas conservadas</dt><dd>{workspace.exportReport.charts}</dd></div><div><dt>Celdas actualizadas</dt><dd>{workspace.exportReport.changedCells}</dd></div><div><dt>Partes del archivo sin cambios</dt><dd>{workspace.exportReport.preservedParts}</dd></div></dl>{workspace.exportReport.warnings.map((w, i) => <p className="muted" key={i}>{w}</p>)}</div><div className="dialog-footer"><button className="button primary" onClick={() => workspace.setExportReport(undefined)}>Cerrar</button></div></Dialog>}
  </div>;
}
